import './src/buttonToDisplayFooter/1header.js';
import './src/buttonToDisplayFooter/2main.js';
import './src/buttonToDisplayFooter/3menu.js';
import './src/buttonToDisplayFooter/4aside.js';
import './src/buttonToDisplayFooter/5section.js';
import './src/buttonToDisplayFooter/6figure.js';
import './src/buttonToDisplayFooter/7footer.js';
import { slider } from './src/logic/slider.js';
import { _1createOrder } from './src/Buttons to Display/1createOrder.js';
import { _2ChooseStoneBtn } from './src/Buttons to Display/2ChooseStoneBtn.js';
import { _3ChoseStoneImg } from './src/Buttons to Display/3ChoseStoneImg.js';
import { _4ConfirmStoneSelectionButton } from './src/Buttons to Display/4ConfirmStoneSelectionButton.js';
import { _5addToBasket } from './src/Buttons to Display/5addToBasket.js';
import { _6goToBasket } from './src/Buttons to Display/6goToBasket.js';
import { _7viewDrawing } from './src/Buttons to Display/7viewDrawing.js';
import { _8viewCutting } from './src/Buttons to Display/8viewCutting.js';
import { _10requestAnInvoice } from './src/Buttons to Display/10requestAnInvoice.js';
import { _12contact } from './src/Buttons to Display/12contact.js';
import { _3choosingStone } from './src/logic/3ChoseStoneImgLogic.js';
import { _4ConfirmStoneSelectionButtonLogic } from './src/logic/4ConfirmStoneSelectionButtonLogic.js';
import { _6goToBasketLogic } from './src/logic/6goToBasketLogic.js';
import { COST } from './src/logic/9calculateCostPerStone.js';
import { _13openMap } from './src/Buttons to Display/13LocationButton.js';
import { setupTextSlider } from './src/logic/setupTextSlider.js';
import { guideMain } from './src/logic/guideMain.js';
import { guideAside } from './src/logic/guideAside.js';

slider();
_1createOrder();
_2ChooseStoneBtn();
_3ChoseStoneImg();
_4ConfirmStoneSelectionButton();
_5addToBasket();
_6goToBasket();
_7viewDrawing();
_8viewCutting();
_10requestAnInvoice();
_12contact();
_3choosingStone();
_4ConfirmStoneSelectionButtonLogic();
_6goToBasketLogic();
COST();
_13openMap();
document.addEventListener('DOMContentLoaded', setupTextSlider);
guideMain();
guideAside();
